export default {
  TEALIUM_PROVIDER: 'TealiumProvider',
  BING_PROVIDER: 'BingProvider',
  ENSIGHTEN_PROVIDER: 'EnsightenProvider',
  FACEBOOK_PROVIDER: 'FacebookProvider',
  FORENSICS_PROVIDER: 'ForensicsProvider',
  GOOGLE_ANALYTICS_PROVIDER: 'GoogleAnalyticsProvider',
  GOOGLE_GLOBAL_SITE_TAG_MANAGER_PROVIDER: 'GoogleGlobalSiteTagManagerProvider',
  HOTJAR_PROVIDER: 'HotjarProvider',
  LINKED_IN_PROVIDER: 'LinkedInProvider',
  MEDIA_MATH_PROVIDER: 'MediaMathProvider',
  NATIVO_PROVIDER: 'NativoProvider',
  PARDOT_PROVIDER: 'PardotProvider',
  TWITTER_PROVIDER: 'TwitterProvider',
};
